name: Deploy Tool Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: tools/profile/
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4